module.exports = {
  "EN": {
    "profile": {
      "join": "Joined Date",
      "generated": "Generated by DuoBot",
      "id": "User ID",
      "role": "Roles",
      "roleInline": "Role"
    }
  },
  "TR": {
    "profile": {
      "join": "Katılım Tarihi",
      "generated": "DuoBot tarafından oluşturuldu.",
      "id": "Kullanıcı ID'si",
      "role": "Sahip olunan roller",
      "roleInline": "Rol"
    }
  }
}
