module.exports = {
  "EN": {
    "profile": {
      "join": "Joined Date",
      "generated": "Generated by DuoBot"
    }
  },
  "TR": {
    "profile": {
      "join": "Katılım Tarihi",
      "generated": "DuoBot tarafından oluşturuldu."
    }
  }
}
